# Generated by Django 4.0.2 on 2022-06-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_user_customer_user10'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user10',
            new_name='user',
        ),
    ]
