# Generated by Django 4.0.2 on 2022-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('carbs', models.FloatField()),
                ('protein', models.FloatField()),
                ('Calorie', models.FloatField()),
                ('fat', models.FloatField()),
            ],
        ),
    ]
